[package]
name = "verseguy-application"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"] }
uuid = { workspace = true }
chrono = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

